import{S as b,i,a as y}from"./assets/vendor-c145bea9.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))n(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const p of r.addedNodes)p.tagName==="LINK"&&p.rel==="modulepreload"&&n(p)}).observe(document,{childList:!0,subtree:!0});function t(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerpolicy&&(r.referrerPolicy=e.referrerpolicy),e.crossorigin==="use-credentials"?r.credentials="include":e.crossorigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function n(e){if(e.ep)return;e.ep=!0;const r=t(e);fetch(e.href,r)}})();const m=document.querySelector(".form"),c=document.querySelector(".gallery");document.querySelector(".gallery-box");const a=document.querySelector(".loader-top"),v=document.querySelector(".loader-bottom");document.querySelector("input");const l=document.querySelector(".load-image");document.querySelector("body");let u=1,d="cat",g=40;const L=new b(".gallery a",{nav:!0,captionDelay:250,captionsData:"alt",close:!0,enableKeyboard:!0,docClose:!0});m.addEventListener("submit",S);l.addEventListener("click",q);async function S(s){if(s.preventDefault(),a.style.display="none",d=s.target.elements.search.value.trim(),!d)return c.innerHTML="",l.style.display="none",i.info({position:"topRight",message:"Error enter any symbols"});try{a.style.display="block";const{data:{hits:n,total:e}}=await f(d,u);n.length>0?(a.style.display="none",c.innerHTML=h(n),L.refresh(),i.success({position:"topRight",message:`We found ${e} photos`}),l.style.display="block"):(c.innerHTML="",i.error({position:"topRight",message:"Sorry, there are no images matching your search query. Please try again!"})),e<=g&&(l.style.display="none")}catch{console.log("Error")}finally{a.style.display="none",m.reset()}const t=document.querySelectorAll(".gallery-item")[0].getBoundingClientRect().height;console.log(t)}function f(s,o){return y.defaults.baseURL="https://pixabay.com",y.get("/api/",{params:{key:"37773269-50f55f614e71cb99e92638715",q:s,image_type:"photo",orientation:"horizontal",safesearch:!0,page:o,per_page:40}})}function h(s=[]){return s.reduce((o,t)=>o+`<li class="gallery-item">
        <a href=${t.largeImageURL}>
          <img class="gallery-img" src =${t.webformatURL} alt=${t.tags}/>
        </a>
        <div class="gallery-text-box">
          <p>Likes: <span class="text-value">${t.likes}</span></p>
          <p>views: <span class="text-value">${t.views}</span></p>
          <p>comments: <span class="text-value">${t.comments}</span></p>
          <p>downloads: <span class="text-value">${t.downloads}</span></p>
      </div>
      </li>`,"")}async function q(s){v.style.display="block";try{u+=1;const{data:{hits:o,totalHits:t}}=await f(d,u),n=Math.ceil(t/g);if(u<n)c.insertAdjacentHTML("beforeend",h(o));else return l.style.display="none",i.info({position:"topRight",message:"We're sorry, but you've reached the end of search results."})}catch(o){console.log(o)}window.scrollBy({top:480,left:100,behavior:"smooth"})}
//# sourceMappingURL=commonHelpers.js.map
