import{S as v,i,a as p}from"./assets/vendor-c145bea9.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))a(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const d of o.addedNodes)d.tagName==="LINK"&&d.rel==="modulepreload"&&a(d)}).observe(document,{childList:!0,subtree:!0});function t(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerpolicy&&(o.referrerPolicy=e.referrerpolicy),e.crossorigin==="use-credentials"?o.credentials="include":e.crossorigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function a(e){if(e.ep)return;e.ep=!0;const o=t(e);fetch(e.href,o)}})();const L=document.querySelector(".form"),c=document.querySelector(".gallery");document.querySelector(".gallery-box");const y=document.querySelector(".loader-top"),m=document.querySelector(".loader-bottom");document.querySelector("input");const n=document.querySelector(".load-image");document.querySelector("body");let l=1,u="cat",f=40;const g=new v(".gallery a",{nav:!0,captionDelay:250,captionsData:"alt",close:!0,enableKeyboard:!0,docClose:!0});L.addEventListener("submit",S);n.addEventListener("click",q);async function S(s){s.preventDefault(),y.style.display="block",l=1,u=s.target.elements.search.value.trim();try{if(!u)return c.innerHTML="",i.info({position:"topRight",message:"Error enter any symbols"});const{data:{hits:r,totalHits:t}}=await h(u,l);r.length>0?(y.style.display="none",c.innerHTML=b(r),g.refresh(),i.success({position:"topRight",message:`We found ${t} photos`}),n.style.display="block"):(c.innerHTML="",i.error({position:"topRight",message:"Sorry, there are no images matching your search query. Please try again!"})),t<=f&&(n.style.display="none")}catch{console.log("Error")}finally{y.style.display="none",s.target.reset()}}function h(s,r){return p.defaults.baseURL="https://pixabay.com",p.get("/api/",{params:{key:"37773269-50f55f614e71cb99e92638715",q:s,image_type:"photo",orientation:"horizontal",safesearch:!0,page:r,per_page:40}})}function b(s=[]){return s.reduce((r,t)=>r+`<li class="gallery-item">
        <a href=${t.largeImageURL}>
          <img class="gallery-img" src =${t.webformatURL} alt=${t.tags}/>
        </a>
        <div class="gallery-text-box">
          <p>Likes: <span class="text-value">${t.likes}</span></p>
          <p>views: <span class="text-value">${t.views}</span></p>
          <p>comments: <span class="text-value">${t.comments}</span></p>
          <p>downloads: <span class="text-value">${t.downloads}</span></p>
      </div>
      </li>`,"")}async function q(s){m.style.display="block",n.style.display="none";const t=document.querySelector(".gallery-item:first-child").getBoundingClientRect().height;try{l+=1;const{data:{hits:a,totalHits:e}}=await h(u,l),o=Math.ceil(e/f);if(n.style.display="block",c.insertAdjacentHTML("beforeend",b(a)),g.refresh(),l===o)return n.style.display="none",i.info({position:"topRight",message:"We're sorry, but you've reached the end of search results."})}catch(a){console.log(a)}finally{m.style.display="none",window.scrollBy({top:2*t,behavior:"smooth"})}}
//# sourceMappingURL=commonHelpers.js.map
