import{S as v,i as c,a as m}from"./assets/vendor-c145bea9.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))l(e);new MutationObserver(e=>{for(const s of e)if(s.type==="childList")for(const y of s.addedNodes)y.tagName==="LINK"&&y.rel==="modulepreload"&&l(y)}).observe(document,{childList:!0,subtree:!0});function t(e){const s={};return e.integrity&&(s.integrity=e.integrity),e.referrerpolicy&&(s.referrerPolicy=e.referrerpolicy),e.crossorigin==="use-credentials"?s.credentials="include":e.crossorigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function l(e){if(e.ep)return;e.ep=!0;const s=t(e);fetch(e.href,s)}})();const g=document.querySelector(".form"),d=document.querySelector(".gallery");document.querySelector(".gallery-box");const i=document.querySelector(".loader-top"),p=document.querySelector(".loader-bottom");document.querySelector("input");const n=document.querySelector(".load-image");document.querySelector("body");let a=1,u="cat",f=40;const L=new v(".gallery a",{nav:!0,captionDelay:250,captionsData:"alt",close:!0,enableKeyboard:!0,docClose:!0});g.addEventListener("submit",S);n.addEventListener("click",q);async function S(r){if(r.preventDefault(),a=1,i.style.display="none",u=r.target.elements.search.value.trim(),!u)return d.innerHTML="",n.style.display="none",c.info({position:"topRight",message:"Error enter any symbols"});try{i.style.display="block";const{data:{hits:o,total:t}}=await h(u,a);o.length>0?(i.style.display="none",d.innerHTML=b(o),L.refresh(),c.success({position:"topRight",message:`We found ${t} photos`}),n.style.display="block"):(d.innerHTML="",c.error({position:"topRight",message:"Sorry, there are no images matching your search query. Please try again!"})),t<=f&&(n.style.display="none")}catch{console.log("Error")}finally{i.style.display="none",g.reset()}}function h(r,o){return m.defaults.baseURL="https://pixabay.com",m.get("/api/",{params:{key:"37773269-50f55f614e71cb99e92638715",q:r,image_type:"photo",orientation:"horizontal",safesearch:!0,page:o,per_page:40}})}function b(r=[]){return r.reduce((o,t)=>o+`<li class="gallery-item">
        <a href=${t.largeImageURL}>
          <img class="gallery-img" src =${t.webformatURL} alt=${t.tags}/>
        </a>
        <div class="gallery-text-box">
          <p>Likes: <span class="text-value">${t.likes}</span></p>
          <p>views: <span class="text-value">${t.views}</span></p>
          <p>comments: <span class="text-value">${t.comments}</span></p>
          <p>downloads: <span class="text-value">${t.downloads}</span></p>
      </div>
      </li>`,"")}async function q(r){p.style.display="block",n.style.display="none";try{a+=1;const{data:{hits:l,totalHits:e}}=await h(u,a),s=Math.ceil(e/f);if(a<s)p.style.display="none",n.style.display="block",d.insertAdjacentHTML("beforeend",b(l));else return p.style.display="none",n.style.display="none",c.info({position:"topRight",message:"We're sorry, but you've reached the end of search results."})}catch(l){console.log(l)}const o=document.querySelector(".gallery-item:first-child"),t=o.getBoundingClientRect().height;console.log(t),console.log(o),window.scrollBy({top:2*t,behavior:"smooth"})}
//# sourceMappingURL=commonHelpers.js.map
